{
    'name': 'UMTTI School Management',
    'version': '18.0.1.0.0',
    'summary': 'Admissions, curriculum, timetabling, schemes of work and attendance for UMTTI',
    'category': 'Education',
    'author': 'Ujuzi Manyattani Training Institute',
    'license': 'LGPL-3',
    'depends': ['base', 'contacts', 'hr'],
    'data': [
        'security/umtti_security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/grade_data.xml',
        'data/course_equipment_data.xml',
        'views/course_views.xml',
        'views/trainer_views.xml',
        'views/exam_views.xml',
        'views/poe_views.xml',
        'views/graduation_views.xml',
        'report/transcript_report.xml',
        'views/student_views.xml',
        'views/menus.xml',
    ],
    'application': True,
    'installable': True,
}
